### ISSUE TITLE
No More Twilio?

### ISSUE THREAD

**Issue by shawnhooper** [laravel-notification-channels/channels#124]
Good morning.

The Twilio channel seems to have disappeared from GitHub.  It's still in your documentation on the website, which is showing the missing repo:

![image](https://user-images.githubusercontent.com/2073284/122046311-c0f0af00-cdac-11eb-89cc-4d3620084e61.png)

Can I get that channel back?

**Comment by lnpbk** [comment]
I was just about to post the same. Completely gone for me

**Comment by shawnhooper** [comment]
@lnpbk  I just set up a copy of the repo from my last build (yesterday).  Feel free to use it until we hear back on this ticket. 

If you'd like to use it, change your composer.json require line to:

`        
"laravel-notification-channels/twilio": "dev-main",
`

and add a custom repository:

```    
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/actionable-co/twilio"
        },
]

**Comment by kalemdzievski** [comment]
I was wondering the same thing.

**Comment by stephenhoult** [comment]
Just an FYI. 

The repo was still available this morning at 9.32am UTC but had gone sometime before 10:16am UTC.

**Comment by drakulovski** [comment]
This issue should be marked as the highest priority, production code affected.

**Comment by kalemdzievski** [comment]
@atymic not sure who to tag here, but will you be able to give us any info on what happened with the repo, or at least referr us to someone how knows. Thanks!

**Comment by olivernybroe** [comment]
I tweeted about this also, but haven't gotten an answer from somebody who knows yet 🙂 
https://twitter.com/OliverNybroe/status/1404790743764541444

**Comment by erikgall** [comment]
If needed by anyone for a temporary fix: https://github.com/erikgall/laravel-twilio-notification-channel

```
composer require erikgall/laravel-twilio-notification-channel
```

**Comment by olivernybroe** [comment]
@erikgall thanks 👍 

Does anyone have a clone of the repo? Not only the composer data. E.g. having the tests folder and so on.

**Comment by erikgall** [comment]
@olivernybroe I can look into getting the tests and anything else still missing, into that repo of mine.. but my bigger concern is why this happened.. Do we still not have any idea what is going on and why this was deleted/made private?

> @erikgall thanks 👍 
> 
> 
> 
> Does anyone have a clone of the repo? Not only the composer data. E.g. having the tests folder and so on.

**Comment by atymic** [comment]
Investigating now, sorry only 7am here in australia.

**Comment by erikgall** [comment]
> Investigating now, sorry only 7am here in australia.

Thank you @atymic

**Comment by atymic** [comment]
Looks like it was deleted by one of the maintainers, working on restore atm.

![Screen Shot 2021-06-16 at 07 07 55](https://user-images.githubusercontent.com/50683531/122123679-9ae11280-ce71-11eb-978b-4c639bb342dd.png)

**Comment by atymic** [comment]
Unfortunately it doesn't seem to be able to be recoverable. I have reached out to github support, if anyone has any contacts feel free to point them to ticket #1195707

![Screen Shot 2021-06-16 at 07 12 19](https://user-images.githubusercontent.com/50683531/122124139-37a3b000-ce72-11eb-80e9-db96c219596a.png)

**Comment by erikgall** [comment]
> Unfortunately it doesn't seem to be able to be recoverable. I have reached out to github support, if anyone has any contacts feel free to point them to ticket #1195707
> 
> 
> 
> ![Screen Shot 2021-06-16 at 07 12 19](https://user-images.githubusercontent.com/50683531/122124139-37a3b000-ce72-11eb-80e9-db96c219596a.png)
> 
> 

@atymic That's not good. Do you happen to have a local copy of the repo? If not hopefully GitHub support and restore it. 

Mostly out of curiosity but I think we all are interested in knowing why this got deleted by the one maintainer.

**Comment by dan-lee** [comment]
ping @fwartner

**Comment by atymic** [comment]
> @atymic That's not good. Do you happen to have a local copy of the repo? If not hopefully GitHub support and restore it.
> 
> Mostly out of curiosity but I think we all are interested in knowing why this got deleted by the one maintainer.

Problem is if I recreate it, we'll loose all issues, PRs, etc. I also only have a copy from Apr 2020, which is def not the latest.

**Comment by fwartner** [comment]
WTF?! I didn't did anything like that! 
Must be something wrong with GitHub.

I am so sorry for that to happen!
If there's anything I can help with, let me know!

I really have no idea, how this could happen!

But also I noticed that there are several repositories missing on my personal profile..

**Comment by atymic** [comment]
@fwartner maybe your account was hacked. I would suggest securing it ASAP then.

**Comment by fwartner** [comment]
ON IT!

I also try to get in contact with GitHub to investigate..

**Comment by bramdevries** [comment]
@fwartner Could you check if the repository is listed in https://github.com/settings/deleted_repositories?

**Comment by atymic** [comment]
I've also removed the ability for maintainers to delete repos now as well.
Waiting on github support ATM.

**Comment by fwartner** [comment]
@bramdevries Nope. There are only repositories deleted from my personal account..

Is there any way to restore the repository on org-level?

**Comment by fwartner** [comment]
Found it:

https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/restoring-a-deleted-repository#restoring-a-deleted-repository-that-was-owned-by-an-organization

**Comment by atymic** [comment]
> docs.github.com/en/github/administering-a-repository/managing-repository-settings/restoring-a-deleted-repository#restoring-a-deleted-repository-that-was-owned-by-an-organization

Unfortunately I tried that, it's not in that list.

**Comment by fwartner** [comment]
> > docs.github.com/en/github/administering-a-repository/managing-repository-settings/restoring-a-deleted-repository#restoring-a-deleted-repository-that-was-owned-by-an-organization
> 
> Unfortunately I tried that, it's not in that list.

That is strange.. 
Ping @mpociot @themsaid Can anyone of you guys check if the repo is still listed?

**Comment by atymic** [comment]
> That is strange..
> Ping @mpociot @themsaid Can anyone of you guys check if the repo is still listed?

I think it's because it was forked, therefore it can't be restored. I'm an org owner so I would be able to restore it.

"A deleted repository can be restored within 90 days, unless the repository was part of a fork network that is not currently empty."

**Comment by shawnhooper** [comment]
Is it possible to look up the forks and see who has the most recent one?

**Comment by shawnhooper** [comment]
I was able to find a cached copy (Google) of the Issues tab from June 8th.   Unfortunately the details on each issue don't appear to be cached.

![image](https://user-images.githubusercontent.com/2073284/122130757-1b6a2980-ce06-11eb-8422-1580d3825a75.png)

**Comment by atymic** [comment]
GitHub support responded and advised it has been restored. Hopefully packagist and other downstream services pick that up shortly.

**Comment by shawnhooper** [comment]
@atymic Thank you for addressing this so quickly.  Appreciate this was probably not how you wanted to wake up this morning :)

**Comment by kalemdzievski** [comment]
@atymic Thank you for resolving this quickly. Have a great day!

**Comment by olivernybroe** [comment]
Thank you @atymic! ♥️

@fwartner hope you figure out what happened and gets all your projects restless 😊
