### ISSUE TITLE
AWS SNS

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/channels#56]
https://github.com/laravel-notification-channels/aws-sns

In progress, see: 
https://github.com/laravel-notification-channels/aws-sns/issues/1

**Comment by atymic** [comment]
cc @mnfgul would you be interested in this one?

> Hi @mpociot @themsaid @freekmurze @e2kaneko,

> I did not noticed these proposal issue so I have created a channel for AWS SNS. You can check it here https://github.com/mnfgul/skeleton.

> I see that aws-sns is already created. However, there is not commits yet. Is it possible to use the channel I created for this.

> Thanks.

**Comment by atymic** [comment]
@clarkeash are you still interested also?

https://github.com/laravel-notification-channels/new-channels/issues/6#issuecomment-269136911

**Comment by clarkeash** [comment]
@atymic No, I don't have a need for this anymore

**Comment by atymic** [comment]
Ok, no worries :)

**Comment by fsavina** [comment]
@atymic I can take this on. I've recently done an SNS integration for a project that I was thinking about converting into a package

**Comment by atymic** [comment]
Hey @fsavina 

That would be awesome!
Feel free to PR against the repo:
https://github.com/laravel-notification-channels/aws-sns

I will review and add you as an admin once merged :)

**Comment by fsavina** [comment]
@atymic ok I'll be in touch as soon as I get some spare time!

**Comment by claudsonm** [comment]
@atymic the repository https://github.com/laravel-notification-channels/aws-sns is empty. Therefore, it can't be forked. I did as instructed on the https://github.com/laravel-notification-channels/channels repo and pushed to that repo for review.

Could you check it out?

**Comment by atymic** [comment]
Channel Live 🎉  Thanks @claudsonm
