### ISSUE TITLE
sipgate

### ISSUE THREAD

**Issue by simonkub** [laravel-notification-channels/channels#65]
Hey,

I wrote a notifications driver to send sms via [sipgate](https://sipgate.de).

Are you interested in publishing it your website and move the code in your organisation?

You can find it here: https://github.com/simonkub/laravel-sipgate-notification

**Comment by atymic** [comment]
@sum

**Comment by atymic** [comment]
Hey @simonkub 

I've created the repo here:
https://github.com/laravel-notification-channels/sipgate

Please PR the code there and we'll review it. Have created an issue to track the launch here:

https://github.com/laravel-notification-channels/sipgate/issues/1

**Comment by atymic** [comment]
Closing this issue as the channel is going live 🎉
