### ISSUE TITLE
Channel Deprecations Proposal

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/channels#67]
I propose to deprecate the following channels

- [x] https://github.com/laravel-notification-channels/evernote
17 downloads in in 3 years
- [x] https://github.com/laravel-notification-channels/wunderlist
28 downloads in in 3 years
- [x] https://github.com/laravel-notification-channels/todoist
60 downloads in in 3 years
- [x] https://github.com/laravel-notification-channels/gammu
Author has decided to abandon the package

If there's no objection I'll begin marking them as abandoned on packagist, updating the readme to indicate they are not maintained and archiving the repos.

**Comment by atymic** [comment]
Closing this as the packages have been deprecated. If you'd like to adopt one, please comment on this issue and we'll consider bringing it back with you as the maintainer.

**Comment by aurawindsurfing** [comment]
Hi, I would like to update https://github.com/laravel-notification-channels/gammu channel to be compatible with version 8 of laravel. I will make a pull request. Will that be sufficient to bring this channel back to life? Thanks!

**Comment by atymic** [comment]
Sure @aurawindsurfing 
I can undeprecate it in that case 👍
