### ISSUE TITLE
Create maintainer list

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/channels#71]
We should create a list of repos, and who maintains each one. That way, if there are issues we know who to contact.

**Comment by atymic** [comment]
Maybe worth keeping it in the website channel so we can use it pragmatically for this feature: https://github.com/laravel-notification-channels/website/issues/4

**Comment by irazasyed** [comment]
How about an `awesome-laravel-notification-channels` list with channel name, author, stars and simple description?

It would serve as a directory and possibly open for addition to other channels that are outside this org as alternate channels (depending on its quality). And ofc with it we'd know who to contact.

**Comment by atymic** [comment]
I don't think that's really necessary. I would toy with the idea of listing 3rd party channels on the website however (would require some changes, but since it's a BC break to move them under over namespace I think it's ok).

Maintainer PR here: https://github.com/laravel-notification-channels/website/pull/11

**Comment by irazasyed** [comment]
Alright, Sounds good. 

I just saw the new changes. Looks good, perfectly aligned and consistent across all pages which makes it easy to know the maintainer 👍
