### ISSUE TITLE
Walletmix Sms channel

### ISSUE THREAD

**Issue by yousuf-hossain-shanto** [laravel-notification-channels/channels#76]
Repo Link - https://github.com/yousuf-hossain-shanto/walletmix-sms-channel

**Comment by atymic** [comment]
Hi @yousuf-hossain-shanto 

As far as I can see, there's no way to sign up for the service on the walletmix site (it seems to be an agency?)

**Comment by yousuf-hossain-shanto** [comment]
Yes, Walletmix is a payment gateway and SMS service provider in Bangladesh

**Comment by atymic** [comment]
Can you provide a link to the sign up and documentation pages please

**Comment by yousuf-hossain-shanto** [comment]
as far as I know, you must contact sales for their SMS API, after the business agreement process they will send you all credentials and links. For reference, you can check bellow link

http://sms.walletmix.biz

**Comment by atymic** [comment]
I don't think it's worth having them as a provider, as it's very niche. We may re-consider in the future if they have an open signup process.

Thanks for the suggestion, though :)
