### ISSUE TITLE
Mandrill Templates

### ISSUE THREAD

**Issue by klimov-paul** [laravel-notification-channels/channels#88]
It would be nice to have a Madnrill notification channel support.
But not the one for raw email, like the old Laravel mail driver, which has been dropped at 6.0.
I am asking about Mandrill template rendering support. See:

https://mandrill.zendesk.com/hc/en-us/articles/205582507-Getting-Started-with-Templates
https://mandrillapp.com/api/docs/templates.JSON.html

There is an existing package, which provides such solution:
https://github.com/techinasia/laravel-mandrill-notification-channel

However it has been abandoned for the 3 years already.

The main problem with Mandrill is its requires enterprise (paid) account even for testing.
Thus, I can not afford myself to maintain such library, as I may not be able to actually test it.

Perhaps the organization like this one could handle it.

**Comment by atymic** [comment]
> Perhaps the organization like this one could handle it.

We're also just volunteers, we have no capital to purchase said plans :(.
Unfortunately I don't think this is a good channel, due to it's expense and niche appeal.
You are of course welcome to maintain your own channel outside of LNC :)
