### ISSUE TITLE
New Channel Suggestion - AfricasTalking (https://africastalking.com/)

### ISSUE THREAD

**Issue by ossycodes** [laravel-notification-channels/channels#92]
[AfricasTalking](https://africastalking.com/) is one of the largest communications solutions in Africa, 
here is the link to the provider's site `https://africastalking.com/`
and a link to the documentation `https://build.at-labs.io/docs/sms%2Foverview`

**Comment by atymic** [comment]
We'd be happy to accept this channel!
Feel free to PR :)

**Comment by ossycodes** [comment]
Hello atymic, I have followed the  workflow for new channel, located here https://github.com/laravel-notification-channels/channels, I however am unable to create a PR, see image
![issue](https://user-images.githubusercontent.com/55060799/76520868-04e75c80-6464-11ea-8e23-7981cc41950d.PNG)

**Comment by ossycodes** [comment]
This is the link to Africastalking channel repository https://github.com/ossycodes/africastalking

**Comment by ossycodes** [comment]
Hey,

I wrote a notifications driver to send sms via AfricasTalking.

Are you interested in publishing it to your website and move the code in your organisation?

You can find it here: https://github.com/ossycodes/africastalking

**Comment by atymic** [comment]
Please PR your code here:
https://github.com/laravel-notification-channels/africastalking

Thanks!
