### ISSUE TITLE
Basecamp Campfire

### ISSUE THREAD

**Issue by Yazan-Stash** [laravel-notification-channels/channels#95]
Hi there, I'd like to PR a channel to integrate with Basecamp 3 Campfires, it's kinda like channels in Slack, and I think other people would benefit from this as well.

**Comment by krizzdev** [comment]
Could this be a solution? https://github.com/joecampo/laravel-notification-basecamp

**Comment by Yazan-Stash** [comment]
Yeah, I guess. I'll go ahead and close this one.
