### ISSUE TITLE
Add Microsoft Teams Channel

### ISSUE THREAD

**Issue by Tob0t** [laravel-notification-channels/channels#97]
I just created a channel for [Microsoft Teams](https://products.office.com/de-at/microsoft-teams/group-chat-software) what I would like to share with you.

**Comment by Tob0t** [comment]
So I followed the instructions from https://github.com/laravel-notification-channels/channels by 
* creating a template from the skeleton
* implementing the logic
* forking the channels repo
* adding the channels repo as remote
* create new branch and pushing

However, creating a PR is not possible due to the following error:
`There isn’t anything to compare.
laravel-notification-channels:master and Tob0t:teams-channel-adaptions are entirely different commit histories.`

I don't get it how the workflow should work since I now have to submit a PR to a repo with different history. Maybe someone can help me what am I missing (sorry, i never worked with templates before)?

Link to my repo: https://github.com/Tob0t/laravel-notification-channel-teams/tree/teams-channel-adaptions ( template from skeleton)
Link to forked repo: https://github.com/Tob0t/channels/tree/teams-channel-adaptions (forked channels)

Any help would be appreciated :)

**Comment by atymic** [comment]
Hey :)

Thanks for the channel. I had a quick look and it looks good. I'll create a blank repo for you, and you can PR there.

https://github.com/laravel-notification-channels/microsoft-teams

Steps: 
1) Clone repo above
2) Copy paste all your files into the clone folder, commit on a branch and PR agaisn't the repo :)

**Comment by atymic** [comment]
Launch checklist here:
https://github.com/laravel-notification-channels/microsoft-teams/issues/1

**Comment by Tob0t** [comment]
Thanks for the instructions, I already create a PR on that repo: https://github.com/laravel-notification-channels/microsoft-teams/pull/2

**Comment by atymic** [comment]
Closing this :D Channel approved
